export const colors = {
    light:{
        red:'#FDEAEC',
        green:'#E8F2EA',
        blue:'#EAF0FF',
        orange:'#FDF6E4'
    },
    dark:{
        green:'#157832',
        red:'#B32C1D',
        blue:'#1472CB',
        orange:'#A26316'
    },
    grey:'grey',
    sliverGrey:'#eeeded',
    lightGrey:'rgba(0,0,0,.2)',
    white:'#fff',
    black:'#222',
    textGrey:'#1f1f1f',
    normalTextColor:'#5e605f',
}